language: php

sudo: false

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: dependencies=lowest

before_script:
  - composer install -n ; fi
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - phpunit
