language: php

services:
  - redis-server

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
